### ISSUE TITLE
Binary Download Link is Borken

### ISSUE THREAD

**Issue by drveresh** [astavonin/Tasks-Explorer#4]
Hi,

We are unable to download the executable from the given link - https://github.com/macosinternals/Tasks-Explorer/blob/master/release/Tasks%20Explorer.pkg?raw=true.  Please update it.

- Thanks

**Comment by astavonin** [comment]
Do not think this version still working. If you are looking for old one, would better to compile it from sources. Sorry :(

**Comment by varenc** [comment]
here ya go @drveresh 

https://github.com/astavonin/Tasks-Explorer/blob/d69564b16ba094c9bafddfb03f546a067a5d2518/release/Tasks%20Explorer.pkg?raw=1

but it is indeed broken.  Fails with a segfault: 11

**Comment by drveresh** [comment]
@varenc Thank you, and I just installed it, but it is not working.  First, it crashed 2-3 times, then it took 45-60sec to load, and finally, it showed an empty list.  This behavior is on my latest Macbook.

I think it needs another fix.

**Comment by varenc** [comment]
As I said, it is indeed broken! Gotta compile or yourself probably =)

**Comment by astavonin** [comment]
Sorry, I do not support this project any more.
